---
title: "*Supplement for*: countfitteR: efficient selection of count distributions to assess DNA damage"
author: "Jarosław Chilimoniuk, Alicja Gosiewska, Jadwiga Słowik, Romano Weiss, Markus Deckert, Stefan Rödiger, and Michał Burdukiewicz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
    number_sections: yes
  html_document:
    always_allow_html: yes
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: no
csl: elsevier-vancouver.csl
bibliography: countfitter.bib
---


# **countfitteR**

Count data, one of the most common data types in many fields. In personalized 
medicine and pharmacology, the analysis is relevant for numerous applications, 
such as cancer and ageing research and in the evaluation of drug efficacy 
[@schneider_open_2019; @redon_recent_2011; 
@lomaxBiologicalConsequencesRadiationinduced2013; @nikolova_h2ax_2014; @martin_statistical_2013]. By 
default it is assumed to follow the Poisson distribution. This assumption, 
however, may lead to biased results and faulty conclusions in data bodies with 
excess zero values (zero-inflation [@limScoreTestsZeroinflation2013; 
@yangTestingOverdispersionZeroinflated2009]), a variance larger than the mean 
(overdispersion), or both. In such cases, the standard assumption of a Poisson 
distribution would skew the estimation of mean and variance, and other models 
like the negative binomial (NB), zero-inflated Poisson or zero-inflated NB 
distributions should be employed. The model chosen has an influence on the 
parameter estimation (mean value and confidence interval). Yet the choice of the 
most suitable distribution model is not trivial. To support and simplify this 
process, we have implemented the 
[countfitteR](https://CRAN.R-project.org/package=countfitteR) software, which is 
provided as an R package and a web server. We show the application of our 
software based on examples of count data from phenotypic imaging as used in 
radiomics and precision medicine: DNA double-strand breaks (DSBs) 
[@reddig_dna_2018]. DSBs are a highly specific and sensitive molecular biomarker 
for monitoring DNA damage in cancer, aging research and the evaluation of drug 
efficacy, and are detected and quantified by foci formation in fluorescence 
microscopy. In analyzing a large number of datasets of a molecular 
pharmacological markers (phosphorylated Histone H2AX and p53 binding protein 
[@ruhe_molecular_2019; @clingen_histone_2008]), 
[countfitteR](https://CRAN.R-project.org/package=countfitteR) demonstrated an 
equal or superior statistical performance compared to the usually employed 
two-step procedure, with an overall power of up to 98 %. In addition, it still 
gave information in cases with no result at all from the two-step procedure. In 
our data sample we found that the NB distribution was the most frequent, with 
the Poisson distribution taking second place. Originally designed for the 
analysis of foci in biomedical image data, 
[countfitteR](https://CRAN.R-project.org/package=countfitteR) can be used in a 
variety of areas where non-Poisson distributed counting data is prevalent.



## General information

### Charts

Each chart may be saved in the `.svg` (Scalable Vectror Graphic) format. A download button is always located at the top of a chart. 

### Tables
Tables may be downloaded in a specified format or printed using the buttons at the top of the table.

## Data upload

The data format suitable for upload is the .csv document, where a single column corresponds to a single count. Use raw counts instead a pivot table. If your document does not have headers, specify it using the "Header" checkbox. In this case, **countfitter** will automatically name your counts with the index number of a count prefixed by 'C'.  

## Count data

This panel contains descriptive statistics and summaries of the input data. It consists of three subpanels:  
1. *Count table*: the input dataset in the tabular format allowing sanity checks and manual modification.
2. *Summary*: summary statistics of the input data (respectively mean, standard deviation, median, median absolute deviate, minimum, maximum, number of elements).  
3. *Distribution*: a bar chart of the counts distribution followed by a pivot table.  

## Fitted models

1. *Mean value estimates*: the estimated value of mean ($\lambda$) and its confidence intervals. The BIC indicates the most appropriate distribution.    
2. *Coefficients*: coefficients of fitted models. 
3. *Decision*: the most appropriate model and the strength of the evidence [@rafteryBayesianModelSelection1995].

## Compare distributions

The bar charts represent theoretical counts depending on the chosen distribution. Red dots describe the real number of counts. The visualized data is also available in the tabular format.

## Settings

**Separate experiments**: if this checkbox is marked, the **countfitter** assumes that experiments are separate and fits the distribution to each individually and independently. Otherwise, all counts are simultaneously fitted to a single model. It is more appropriate for situations, where there is assumption that all samples may be describe by the same distribution, for example in case of technical replicates.  

**Confidence level**: the confidence level of confidence intervals.  

**Count distributions**: count distributions fitted to data: Poisson, Negative Binomial, Zero-Inflated Poisson, Zero-Inflated Negative Binomial. Possible distributions are described further in the manual.  

# Overdispersion

One of the important features of the Poisson distribution is the equality of variance and expected value. Although count data is commonly assumed to be Poisson-distributed, we often encounter overdispersed datasets, when the variance is bigger than the mean. Three distributions included in **countfitter**: Zero-Inflated Poisson (ZIP), Negative Binomial (NB) and Zero-negative Binomial (ZINB) model overdispersed counts. 

Overdispersion may be caused by the increased variability of counts, for example when a counting algorithm under- and overcounts. In such situation the data might have the NB distribution. The other cause of overdispersion is called zero-inflation and occurs in datasets, where some factor introduced faulty zeros. That means that some counts, regardless of their real state, are treated as zeros. In this case, data has the ZIP distribution. If both faulty zeros and increased variance affect the data, the ZINB distribution is the most appropriate.  

## Overdispersed count data distribution

Poisson and Negative Binomial distributions have the same expected value. In case of ZIP and ZINB, the expected value is smaller than the real average number of foci per cell.

**Table S1**: Expected value and variance of Poisson, ZIP, NB and ZINB distributions. $\lambda$: Poisson parameter (number of occurrences, e.g., average number of foci per cell). $r$: zero inflation (fraction of occurrences treated as zeros, e.g., fraction of cells treated by system as having no foci regardless of their real state). $\theta$: dispersion parameter.

Distribution <br> name  | Expected value | Variance
-------------------|-------------|-----------------------
Poisson            |$$E(X) = \lambda $$            |$$\textrm{var}(X) = \lambda $$
ZIP                |$$E(X) = (1 - r) \lambda $$                |$$\textrm{var}(X) = \lambda (1 - r)(1 + \lambda r)$$
NB                 |$$E(X) = \lambda $$                 |$$\textrm{var}(X) = \lambda + \frac{\lambda^2}{\theta} $$
ZINB               |$$E(X) = (1 - r)  \lambda $$               |$$\textrm{var}(X) = (1 - r) \lambda \left( 1 + r\lambda  + \frac{1}{\theta} \right)$$  <!-- keep it here, because otherwise table parse oddly  -->

Depending on the value of $r$ the variance of ZIP and ZINB may be smaller or bigger than the variance of Poisson distribution. In case of the NB distribution, the variance is always bigger than for the Poisson distribution, although the difference becomes negligible, when the $\theta$ is much bigger than $\lambda^2$.

Parameters:

* $\lambda$ - Poisson parameter (average number of foci per cell).  
* $r$ - zero inflation (fraction of cells treated by system as having no foci regardless of their real state).  
* $\theta$ - dispersion parameter.
  
Usually the NB distribution is parameterized using $\mu$ and $\theta$, but to make comparison clearer, we use $\lambda$ instead of $\mu$. In this parameterization, NB and ZINB are treated as the mixture of Poisson and Gamma ($\Gamma$) distributions.  

**Table S2**: Probability mass functions of Poisson, ZIP, NB and ZINB distributions. $\lambda$: Poisson parameter (number of occurrences, e.g., average number of foci per cell). $r$: zero inflation (fraction of occurrences treated as zeros, e.g., fraction of cells treated by system as having no foci regardless of their real state). $\theta$: dispersion parameter.

Distribution <br> name  | pmf 
-------------------|-------------
Poisson            |$$P\{X = k\} = \frac{\lambda^k \exp^{-\lambda}}{k!} $$
Zero-inflated Poisson                |$$P\{X = k\} = \begin{cases} r + ( 1- r) \exp^{-\lambda},\text{if } k = 0\\ r \frac{\lambda^k \exp^{-\lambda}}{k!},\text{if } k = 1, 2, \ldots \end{cases} $$
Negative Binomial                 |$$P\{X = k\} = \frac{\Gamma (\theta + k)}{\Gamma(\theta) k!}  \left(\left( \frac{\theta}{\theta + \lambda} \right)^\theta \left( \frac{\lambda}{\theta + \lambda} \right) \right)^k$$
Zero-inflated Negative Binomial               |$$P\{X = k\} = \begin{cases}r + (1 - r) \left( \frac{\theta}{\theta + \lambda} \right)^\theta,\text{if } k = 0\\(1 - r) \frac{\Gamma (\theta + k)}{\Gamma(\theta) k!}  \left(\left( \frac{\theta}{\theta + \lambda} \right)^\theta \left( \frac{\lambda}{\theta + \lambda} \right) \right)^k,\text{if } k = 1, 2, \ldots\end{cases}$$


# References
