---
title: "Methods comparison bars"
author: "Alicja Gosiewska"
date: "5 07 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
#devtools::install_github("teunbrand/ggh4x")
library(ggh4x)
library(ggplot2)
library(dplyr)
library(tidyr)
iter <- 100
```


```{r}
load("../data/bic_sim_zip.rda")
load("../data/bic_sim_zinb.rda")
load("../data/bic_sim_pois.rda")
load("../data/bic_sim_nb.rda")
load("../data/twostep_sim_zip.rda")
load("../data/twostep_sim_zinb.rda")
load("../data/twostep_sim_pois.rda")
load("../data/twostep_sim_nb.rda")
```

# Poisson

```{r}
sim_pois <- rbind(bic_sim_pois, twostep_sim_pois)
sim_pois[["selected"]] <- iter - sim_pois[["na"]]
sim_pois[["good"]] <- sim_pois[["selected"]] * sim_pois[["pow_mean"]]
sim_pois[["bad"]] <- sim_pois[["selected"]] * (1-sim_pois[["pow_mean"]])

sim_pois %>%
  pivot_longer(cols = c(na, good, bad), names_to = "result", values_to = "counts") %>%
  mutate(result = factor(result, levels = c("na", "bad", "good"))) %>%
  ggplot(aes(x = "", y = counts, fill = result)) +
    geom_bar(position = "stack", stat = "identity", color = "black") +
    facet_nested(n~lambda+method, labeller = label_both) +
    scale_fill_manual(values = c('#f7f7f7', '#ef8a62','#67a9cf')) +
    theme_bw() 

```


# Zero-inflated Poisson

```{r}
sim_zip <- rbind(bic_sim_zip, twostep_sim_zip)
sim_zip[["selected"]] <- iter - sim_zip[["na"]]
sim_zip[["good"]] <- sim_zip[["selected"]] * sim_zip[["pow_mean"]]
sim_zip[["bad"]] <- sim_zip[["selected"]] * (1-sim_zip[["pow_mean"]])

sim_zip %>%
  pivot_longer(cols = c(na, good, bad), names_to = "result", values_to = "counts") %>%
  mutate(result = factor(result, levels = c("na", "bad", "good"))) %>%
  ggplot(aes(x = r, y = counts, fill = result)) +
    geom_bar(position = "stack", stat = "identity", color = "black") +
    facet_nested(n~lambda+method, labeller = label_both) +
    scale_fill_manual(values = c('#f7f7f7', '#ef8a62','#67a9cf')) +
    theme_bw() 

```


# Negative Binomial

```{r}
sim_nb <- rbind(bic_sim_nb, twostep_sim_nb)
sim_nb[["selected"]] <- iter - sim_nb[["na"]]
sim_nb[["good"]] <- sim_nb[["selected"]] * sim_nb[["pow_mean"]]
sim_nb[["bad"]] <- sim_nb[["selected"]] * (1-sim_nb[["pow_mean"]])

sim_nb[["size_scale"]] <- sim_nb[["lambda"]] / sim_nb[["size"]]
scales <- sim_nb[["size_scale"]] %>% unique()


for(ith_scale in scales){
  p <- sim_nb %>%
      filter(size_scale == ith_scale) %>%
      pivot_longer(cols = c(na, good, bad), names_to = "result", values_to = "counts") %>%
      mutate(result = factor(result, levels = c("na", "bad", "good"))) %>%
      ggplot(aes(x = "", y = counts, fill = result)) +
        geom_bar(position = "stack", stat = "identity", color = "black") +
        facet_nested(n~lambda+method, labeller = label_both) +
        scale_fill_manual(values = c('#f7f7f7', '#ef8a62','#67a9cf')) +
        theme_bw() + 
        ggtitle(paste("scale = lambda *", ith_scale))
  plot(p)
}
```

# Zero-inflated Negative Binomial

```{r, results='asis'}
sim_zinb <- rbind(bic_sim_zinb, twostep_sim_zinb)
sim_zinb[["selected"]] <- iter - sim_zinb[["na"]]
sim_zinb[["good"]] <- sim_zinb[["selected"]] * sim_zinb[["pow_mean"]]
sim_zinb[["bad"]] <- sim_zinb[["selected"]] * (1-sim_zinb[["pow_mean"]])

sim_zinb[["size_scale"]] <- sim_zinb[["lambda"]] / sim_zinb[["size"]]
scales <- sim_zinb[["size_scale"]] %>% unique()


for(ith_scale in scales){
  p <- sim_zinb %>%
      filter(size_scale == ith_scale) %>%
      pivot_longer(cols = c(na, good, bad), names_to = "result", values_to = "counts") %>%
      mutate(result = factor(result, levels = c("na", "bad", "good"))) %>%
      ggplot(aes(x = r, y = counts, fill = result)) +
        geom_bar(position = "stack", stat = "identity", color = "black") +
        facet_nested(n~lambda+method, labeller = label_both) +
        scale_fill_manual(values = c('#f7f7f7', '#ef8a62','#67a9cf')) +
        theme_bw() + 
        ggtitle(paste("scale = lambda *", ith_scale))
  plot(p)
}


```









