---
title: "Methods comparison"
author: "Alicja Gosiewska"
date: "5 07 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
load("../data/bic_sim_zip.rda")
load("../data/bic_sim_zinb.rda")
load("../data/bic_sim_pois.rda")
load("../data/bic_sim_nb.rda")
load("../data/twostep_sim_zip.rda")
load("../data/twostep_sim_zinb.rda")
load("../data/twostep_sim_pois.rda")
load("../data/twostep_sim_nb.rda")
```

# Poisson

```{r}
sim_pois <- rbind(bic_sim_pois, twostep_sim_pois)

ggplot(sim_pois, aes(x = method, y = pow_mean, 
                         ymin = pow_mean - pow_sd, ymax = pow_mean + pow_sd,
                         color = method)) +
  geom_errorbar() +
  geom_point() + 
  geom_hline(yintercept=1, linetype="dashed") +
  geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(lambda~n, labeller = label_both) +
  theme_bw() +
  ylim(-0.2, 1.2)

```


# Zero-inflated Poisson

```{r}
sim_zip <- rbind(bic_sim_zip, twostep_sim_zip)

ggplot(sim_zip, aes(x = r, y = pow_mean, color = method,
                    ymin = pow_mean - pow_sd, ymax = pow_mean + pow_sd,)) + 
  geom_errorbar(alpha = 0.3) +
  geom_point() +
  geom_line(linetype = "dashed") +
  facet_grid(lambda~n, labeller = label_both) +
  theme_bw()

```


# Negative Binomial

```{r}
sim_nb <- rbind(bic_sim_nb, twostep_sim_nb)

ggplot(sim_nb, aes(x = paste0(method, ", size = ", size), y = pow_mean, 
                         ymin = pow_mean - pow_sd, ymax = pow_mean + pow_sd,
                         color = method)) +
  geom_errorbar() +
  geom_point() +
  geom_hline(yintercept=1, linetype="dashed") +
  geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(lambda~n, labeller = label_both) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))
```

# Zero-inflated Negative Binomial

```{r, results='asis'}
sim_zinb <- rbind(bic_sim_zinb, twostep_sim_zinb)
sim_zinb[["size_scale"]] <- sim_zinb[["lambda"]] / sim_zinb[["size"]]
scales <- sim_zinb[["size_scale"]] %>% unique()

for(ith_scale in scales){
  p <- sim_zinb %>%
    filter(size_scale == ith_scale) %>%
      ggplot(aes(x = r, y = pow_mean, color = method,
                    ymin = pow_mean - pow_sd, ymax = pow_mean + pow_sd)) + 
        geom_errorbar(alpha = 0.3) +
        geom_point() +
        geom_line(linetype = "dashed") +
        facet_grid(lambda~n, labeller = label_both) +
        theme_bw() +
        ggtitle(paste("scale = lambda *", ith_scale))
  plot(p)
}


```









